Update terminalscript

diff --git a/terminalscript b/terminalscript
--- a/terminalscript
+++ b/terminalscript
@@ -2,82 +2,60 @@
 
 BASE_DIR="$(cd "$(dirname "$0")"; pwd)" || exit 2
 
-# Initialize password variables
-CURRENT_PASSWORD="admin"  # Change this to your desired initial password
-PASSWORD_ATTEMPTS=3  # Number of attempts before failure
+# File to store the password
+PASSWORD_FILE="$BASE_DIR/password.txt"
 
-IFS=$'\n'
-entrylist=('Go Back')
-rawentry="$(find $BASE_DIR/entries -type f)"
-for i in $rawentry; do
-    i=${i##*/}
-    entrylist+=("$i")
-done
+# Set an initial password if the password file does not exist
+if [ ! -f "$PASSWORD_FILE" ]; then
+    echo "Enter an initial password:"
+    read -s initial_password
+    echo "$initial_password" > "$PASSWORD_FILE"
+fi
 
-COLUMNS=12
+# Function to check the password
+check_password() {
+    local input_password
+    read -sp "Enter password: " input_password
+    echo
 
-# Function to prompt for the password
-prompt_for_password() {
-    local attempt=0
-    while (( attempt < PASSWORD_ATTEMPTS )); do
-        read -s -p "Enter password: " password_input
-        echo
-        if [[ "$password_input" == "$CURRENT_PASSWORD" ]]; then
-            echo "Access granted."
-            return 0
-        else
-            echo "Incorrect password. Try again."
-            ((attempt++))
-        fi
-    done
-    echo "Too many failed attempts. Exiting..."
-    exit 1
+    # Read the stored password from file
+    local stored_password
+    stored_password=$(<"$PASSWORD_FILE")
+
+    if [ "$input_password" == "$stored_password" ]; then
+        return 0
+    else
+        echo "Incorrect password. Please try again."
+        return 1
+    fi
 }
 
 # Function to change the password
 change_password() {
-    read -s -p "Enter new password: " new_password
+    read -sp "Enter new password: " new_password
     echo
-    read -s -p "Confirm new password: " confirm_password
-    echo
-    if [[ "$new_password" == "$confirm_password" ]]; then
-        CURRENT_PASSWORD="$new_password"
-        echo "Password changed successfully."
-    else
-        echo "Passwords do not match. Password not changed."
-    fi
+    echo "$new_password" > "$PASSWORD_FILE"
+    echo "Password changed successfully."
 }
 
-# Function to log out
-logout() {
-    echo "Logging out..."
-    exit 0
+# Function to display login page
+login() {
+    while ! check_password; do
+        echo "Failed to login. Try again."
+    done
 }
 
-# This function is to display the top header in a centered alignment
-display_center(){
-    columns="$(tput cols)"
-    while IFS= read -r line; do
-        printf "%*s\n" $(( (${#line} + columns) / 2)) "$line"
-    done < "$1"
-}
-
-# This string is to be displayed as a custom "title header" at the top
-greeter=$'
-Personal Terminal 
-___________________________________________________'
+# Your existing functions here...
 
 # Main Menu Screen
 mainmenufunc () {
     clear
-
-    # Display the Menu text
     display_center "$BASE_DIR/greeterheader.txt" | pv -qL 80
     echo "$greeter" | pv -qL 80
     echo What would you like to do? | pv -qL 80
 
-    # Define the menu options
-    options=("View Journal Entries" "Log a Journal Entry" "Delete a Journal Entry" "Network Settings" "Reboot Program" "Proceed to Desktop" "Change Password" "Log Out")
+    # Define the menu options including new options
+    options=("View Journal Entries" "Log a Journal Entry" "Delete a Journal Entry" "Network Settings" "Change Password" "Return to Login Page" "Proceed to Desktop")
 
     # Use fzf to display the options
     menuchoice=$(printf "%s\n" "${options[@]}" | fzf --height=10 --border --layout=reverse)
@@ -95,200 +73,23 @@ mainmenufunc () {
         "Network Settings")
             networkfunc
             ;;
-        "Reboot Program")
-            rebootfunc
+        "Change Password")
+            change_password
+            ;;
+        "Return to Login Page")
+            login
             ;;
         "Proceed to Desktop")
             echo Goodbye! && exit
             ;;
-        "Change Password")
-            change_password
-            repeatmainmenufunc
-            ;;
-        "Log Out")
-            logout
-            ;;
         *)
             repeatmainmenufunc
             ;;
     esac
 }
 
-# Option 1 Menu, Viewing Journal Entries
-viewentriesfunc () {
-    entrylist=('Go Back')
-    rawentry="$(find $BASE_DIR/entries -type f)"
-    for i in $rawentry; do
-        i=${i##*/}
-        entrylist+=("$i")
-    done
-
-    clear
-    display_center "$BASE_DIR/greeterheader.txt"
-    echo "$greeter" 
-    echo "Which Journal Entry would you like to access?" | pv -qL 80
-
-    # Use fzf to select an entry
-    readoption=$(printf "%s\n" "${entrylist[@]}" | fzf --height=10 --border --layout=reverse)
-
-    case $readoption in
-        "Go Back")
-            repeatmainmenufunc
-            ;;
-        *)
-            clear
-            display_center "$BASE_DIR/greeterheader.txt"
-            echo "$greeter"
-            echo
-            echo "$readoption:" | pv -qL 80
-            cat "$BASE_DIR/entries/$readoption" | pv -qL 80
-            echo
-            read -p "Press enter to continue"
-            repeatmainmenufunc
-            ;;
-    esac
-}
-
-# Menu for writing an entry
-writeentryfunc () {
-    clear
-    display_center "$BASE_DIR/greeterheader.txt"
-    echo "$greeter" 
-    echo "What would you like to name the entry?" | pv -qL 80
-
-    # Read user input for entry name
-    read entrynameinput 
-
-    clear
-    display_center "$BASE_DIR/greeterheader.txt"
-    echo "$greeter" 
-    echo "Press CTRL+D to finalize entry" | pv -qL 80
-    echo "$entrynameinput:" | pv -qL 80
-    echo
-
-    # Use cat to create the entry
-    cat >"$BASE_DIR/entries/$entrynameinput"
-    cat "$BASE_DIR/entries/$entrynameinput"
-    clear
-
-    repeatmainmenufunc
-}
-
-# Menu to delete an entry
-deleteentryfunc () {
-    entrylist=('Go Back')
-    rawentry="$(find $BASE_DIR/entries -type f)"
-    for i in $rawentry; do
-        i=${i##*/}
-        entrylist+=("$i")
-    done
-
-    clear
-    display_center "$BASE_DIR/greeterheader.txt"
-    echo "$greeter" 
-    echo "Which Journal Entry would you like to delete?" | pv -qL 80
-
-    # Use fzf to select an entry for deletion
-    readoption=$(printf "%s\n" "${entrylist[@]}" | fzf --height=10 --border --layout=reverse)
-
-    case $readoption in
-        "Go Back")
-            repeatmainmenufunc
-            ;;
-        *)
-            clear
-            display_center "$BASE_DIR/greeterheader.txt"
-            echo "$greeter"
-            echo
-            echo "Delete $readoption? Type YES to continue" | pv -qL 80
-
-            # Confirm deletion
-            read confirmdeletion
-            if [[ ${confirmdeletion^^} == "YES" ]]; then
-                rm -f "$BASE_DIR/entries/$readoption"
-                echo "FILE DELETED!"
-                sleep 0.1
-                repeatmainmenufunc
-            else
-                echo "OPERATION CANCELLED"
-                sleep 0.2
-                repeatmainmenufunc
-            fi
-            ;;
-    esac
-}
-
-# Function to display network settings
-networkfunc () {
-    clear
-    display_center "$BASE_DIR/greeterheader.txt"
-    echo "$greeter" 
-    echo "Fetching Network Settings..." | pv -qL 80
-    echo
-
-    # Display network information using ifconfig or ip addr
-    if command -v ifconfig &> /dev/null; then
-        ifconfig | pv -qL 80
-    elif command -v ip &> /dev/null; then
-        ip addr | pv -qL 80
-    else
-        echo "No network information tools found!" | pv -qL 80
-    fi
-
-    echo
-    read -p "Press enter to return to the main menu"
-    repeatmainmenufunc
-}
-
-# Function to reboot the program
-rebootfunc () {
-    echo "Rebooting program..." | pv -qL 80
-    sleep 1
-    exec "$0"  # Re-execute the current script
-}
-
-# Same as the main menu function, but without the animations
-repeatmainmenufunc () {
-    clear
-    display_center "$BASE_DIR/greeterheader.txt"
-    echo "$greeter" 
-    echo What would you like to do? | pv -qL 80
-    options=("View Journal Entries" "Log a Journal Entry" "Delete a Journal Entry" "Network Settings" "Reboot Program" "Proceed to Desktop" "Change Password" "Log Out")
-
-    # Use fzf for repeated main menu
-    menuchoice=$(printf "%s\n" "${options[@]}" | fzf --height=10 --border --layout=reverse)
-
-    case $menuchoice in
-        "View Journal Entries")
-            viewentriesfunc
-            ;;
-        "Log a Journal Entry")
-            writeentryfunc
-            ;;
-        "Delete a Journal Entry")
-            deleteentryfunc
-            ;;
-        "Network Settings")
-            networkfunc
-            ;;
-        "Reboot Program")
-            rebootfunc
-            ;;
-        "Proceed to Desktop")
-            echo Goodbye! && exit
-            ;;
-        "Change Password")
-            change_password
-            repeatmainmenufunc
-            ;;
-        "Log Out")
-            logout
-            ;;
-        *)
-            repeatmainmenufunc
-            ;;
-    esac
-}
+# Add the login call before launching the main menu
+login
 
 # Some random aesthetic startup text
 clear
@@ -311,7 +112,5 @@ echo $'
 echo "==============================================" | pv -qL 50
 sleep 1
 
-# Prompt for the password before accessing the main menu
-prompt_for_password
 # Launch the main menu
 mainmenufunc
